### ISSUE TITLE
메인페이지를 구성한다

### ISSUE THREAD

**Issue by GyeongyeonAn** [DonggukBOB/dongguk-bob#10]
메인페이지를 구현한다.

- 제목 : 동국밥
- 부제목 : 지친 당신의 허기를 달래줄 든-든한
- image (국밥 이미지 로고)
- 버튼 2개
  1. 메뉴 추천
  2. 맛집 목록

적절한 위치 조정

**Comment by win9612** [comment]
확인했습니다. 👍
