### ISSUE TITLE
추천페이지를 구성한다

### ISSUE THREAD

**Issue by win9612** [DonggukBOB/dongguk-bob#14]
<배치 - 추천버튼 누르기 전>
[헤더] - 공통
[필터]
[음식 이미지들 왼쪽으로 슬라이드]
[추천받기 버튼]
[음식 이미지들 오른쪽으로 슬라이드]

- 버튼 : 전체 width의 80% 정도, "Go!" , 화면 정 중앙 배치, 주황색 계열 색깔을 쓰지만 헤더 색깔과 겹치지 않는 색으로

전체적인 구성은 노션에 올려놓은 페이지 구상도 이미지와 비슷하게 할 것 같습니다.

**Comment by GyeongyeonAn** [comment]
[필터]
[음식 이미지들 왼쪽으로 슬라이드]
**- 어떤 의미인지 잘 모르겠어요! 설명해주실 수 있을까요?**

[추천받기 버튼]
[음식 이미지들 오른쪽으로 슬라이드]
**- 수정이 필요할 것 같아요! 추천은 1개만 해주기로 한걸로 기억해요!**

**Comment by win9612** [comment]
> [필터]
> [음식 이미지들 왼쪽으로 슬라이드]
> **- 어떤 의미인지 잘 모르겠어요! 설명해주실 수 있을까요?**
> 
> [추천받기 버튼]
> [음식 이미지들 오른쪽으로 슬라이드]
> **- 수정이 필요할 것 같아요! 추천은 1개만 해주기로 한걸로 기억해요!**

=> 화면에 필터랑 버튼 하나만 떠 있으면 너무 심심할까봐 조금 데코레이션하면 어떨까 생각했습니다. 의도한 바는 여러가지 아무 음식 이미지들을 회전초밥처럼 옆으로 서서히 슬라이드하는 애니메이션을 한번 만들어보고 싶었어요.
추천결과랑 별개입니다😀

버튼 하나만 있어도 괜찮다, 혹은 다른 꾸밈 효과를 주면 어떻겠나 하는 추가 의견도 환영입니다.

**Comment by GyeongyeonAn** [comment]
아하 디자인이였군요, 제가 오해를 했습니다.
결과물이 궁금해지네요! 화이팅
