### ISSUE TITLE
임시 가게 데이터셋을 구성한다

### ISSUE THREAD

**Issue by hwookim** [DonggukBOB/dongguk-bob#18]
추천 로직 및 목록 표시를 위한 가게 데이터셋을 임시로 구성한다.

필요 정보
- 가게이름
- 전화번호
- 위치
- 사진
- 카테고리
- 평점
- 코멘트
- 대표 메뉴 / 가격
- 네이버/카카오 링크

**Comment by GyeongyeonAn** [comment]
좋아요! 임시로 만들어주면 나중에 저희도 데이터 셋을 만들때 참고가 되겠네요!
