### ISSUE TITLE
가게 정보를 표현할 모달창을 구현한다

### ISSUE THREAD

**Issue by hwookim** [DonggukBOB/dongguk-bob#20]
추천 페이지, 목록 페이지, 지도 페이지를 통해서 접근할 수 있는 가게 정보 모달창을 구현합니다.

#18 에서 구성해둔 임시 가게 데이터셋의 정보를 표현합니다.

참고 사진

![스크린샷 2021-05-20 오후 1 49 30](https://user-images.githubusercontent.com/45786387/118920906-34e89480-b972-11eb-9c1a-185cfa777cbb.png)
![스크린샷 2021-05-20 오후 1 49 58](https://user-images.githubusercontent.com/45786387/118920953-4631a100-b972-11eb-9e47-7ed33628fa7c.png)

**Comment by GyeongyeonAn** [comment]
오오 저 디자인 좋습니다!
